---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
---
apiVersion: v1
kind: Namespace
metadata:
  name: blue-green
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
